-- 香港、澳门大学初始数据
-- 注意：rank是MySQL保留字，需要用反引号包裹

-- 清除现有数据
DELETE FROM schools;

-- 香港大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('香港大学', 'The University of Hong Kong', '香港', '香港岛薄扶林', 1, 'https://www.hku.hk/media/images/2023/05/08/MainCampusAerialView.jpg', '香港大学（HKU）是香港历史最悠久的高等教育机构，成立于1911年。QS世界大学排名常年位居全球前30，亚洲前5。作为亚洲顶尖研究型大学，港大以卓越的学术水平、创新的研究项目和国际化视野著称。', '["QS世界大学排名前30","亚洲顶尖研究型大学","国际化程度高","师资力量雄厚","就业前景广阔"]', '{"本科":"高考成绩达一本线以上150分，英语单科130+","硕士":"持有本科学位，GPA 3.0+，雅思6.5+"}', '[{"name":"工程学院","majors":["土木工程","计算机科学","电子工程","机械工程","航空航天工程","生物医学工程"]},{"name":"商学院","majors":["会计学","金融学","经济学","工商管理","市场营销","人力资源管理"]},{"name":"医学院","majors":["医学","牙医学","护理学","药剂学","公共卫生"]},{"name":"文学院","majors":["语言学","文学","历史学","哲学","艺术史"]},{"name":"法学院","majors":["法学","法学博士","国际法","商法"]}]', '[{"name":"商科类","majors":["金融学","会计学","商业分析","市场营销","供应链管理"]},{"name":"工程类","majors":["计算机科学","电子工程","数据科学","人工智能"]},{"name":"医学类","majors":["公共卫生","流行病学","护理学"]}]', 'HKD 182,000-216,000/年', 'https://www.hku.hk', 1, 0);

-- 香港中文大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('香港中文大学', 'The Chinese University of Hong Kong', '香港', '新界沙田', 2, 'https://www.cuhk.edu.hk/images/header/banner-campus.jpg', '香港中文大学（CUHK）成立于1963年，是香港唯一实行书院联邦制的大学。QS世界大学排名前50，亚洲顶尖综合性大学。中大以"结合传统与现代，融会中国与西方"为使命，在人文社科、医学等领域享有盛誉。', '["QS世界大学排名前50","书院制度特色教育","人文社科见长","研究实力雄厚","校园环境优美"]', '{"本科":"高考成绩达一本线以上130分，英语单科120+","硕士":"持有本科学位，GPA 3.0+，雅思6.5+"}', '[{"name":"文学院","majors":["中国语言文学","英文","历史学","哲学","翻译","文化研究"]},{"name":"商学院","majors":["会计学","金融学","工商管理","市场营销","商业分析"]},{"name":"工程学院","majors":["计算机科学","电子工程","信息工程","机械工程","自动化"]},{"name":"医学院","majors":["医学","护理学","公共卫生","中医学","药剂学"]},{"name":"理学院","majors":["数学","物理学","化学","生物化学","统计学"]}]', '[{"name":"商科类","majors":["金融学","会计学","工商管理","商业分析"]},{"name":"理工类","majors":["计算机科学","电子工程","数据科学","人工智能"]},{"name":"医学类","majors":["公共卫生","护理学","中医学"]}]', 'HKD 145,000-180,000/年', 'https://www.cuhk.edu.hk', 1, 0);

-- 香港科技大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('香港科技大学', 'The Hong Kong University of Science and Technology', '香港', '新界西贡清水湾', 3, 'https://www.hkust.edu.hk/sites/default/files/2022-10/campus_aerial_1.jpg', '香港科技大学（HKUST）成立于1991年，是香港最年轻的公立研究型大学。QS世界大学排名前50，工程技术类学科全球领先。科大以创新的教学方法、一流的研究设施和强大的业界联系著称。', '["QS世界大学排名前50","工程技术类全球领先","就业率最高","科研实力强","国际化师资"]', '{"本科":"高考成绩达一本线以上140分，英语单科130+","硕士":"持有本科学位，GPA 3.0+，雅思6.5+"}', '[{"name":"工学院","majors":["计算机科学","电子工程","土木工程","机械工程","化学工程","环境工程"]},{"name":"商学院","majors":["金融学","会计学","经济学","工商管理","商业分析","信息系统"]},{"name":"理学院","majors":["数学","物理学","化学","海洋科学","生命科学"]}]', '[{"name":"商科类","majors":["金融学","会计学","商业分析","经济学","信息系统管理"]},{"name":"工科类","majors":["计算机科学","电子工程","数据科学","人工智能","机械工程"]}]', 'HKD 155,000-200,000/年', 'https://www.hkust.edu.hk', 1, 0);

-- 香港城市大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('香港城市大学', 'City University of Hong Kong', '香港', '九龙九龙塘', 4, 'https://www.cityu.edu.hk/cityu/images/2022/01/banner-campus.jpg', '香港城市大学（CityU）成立于1984年，是香港最大的公立研究型大学之一。QS世界大学排名前100，在工程学、电脑科学等领域表现卓越。城大以"敬业乐群"为校训，注重培养学生的实践能力。', '["QS世界大学排名前100","就业率高","工程学领先","位于市中心","国际化程度高"]', '{"本科":"高考成绩达一本线以上100分，英语单科120+","硕士":"持有本科学位，GPA 3.0+，雅思6.5+"}', '[{"name":"工学院","majors":["电脑科学","电子工程","土木工程","机械工程","生物医学工程","材料工程"]},{"name":"商学院","majors":["会计学","金融学","工商管理","市场营销","经济学","商业分析"]},{"name":"人文社会科学院","majors":["语言学","心理学","社会学","公共政策","媒体与传播"]},{"name":"法学院","majors":["法学","法学博士","仲裁与争议解决"]}]', '[{"name":"商科类","majors":["金融学","会计学","商业分析","工商管理","市场营销"]},{"name":"工科类","majors":["电脑科学","电子工程","数据科学","人工智能","网络安全"]},{"name":"社科类","majors":["心理学","社会学","公共政策","传媒学"]}]', 'HKD 140,000-175,000/年', 'https://www.cityu.edu.hk', 1, 0);

-- 香港理工大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('香港理工大学', 'The Hong Kong Polytechnic University', '香港', '九龙红磡', 5, 'https://www.polyu.edu.hk/pao/images/2023/11/PolyU_Campus_Overview.jpg', '香港理工大学（PolyU）成立于1937年，是香港历史最悠久的专业技术型大学。QS世界大学排名前100，酒店管理、设计等专业全球领先。理工大注重实践与创新，培养应用型专业人才。', '["QS世界大学排名前100","酒店管理全球第一","设计学院全球前20","就业率极高","地理位置优越"]', '{"本科":"高考成绩达一本线以上100分，英语单科110+","硕士":"持有本科学位，GPA 2.8+，雅思6.0+"}', '[{"name":"工商管理学院","majors":["会计学","金融学","工商管理","酒店管理","旅游管理","物流管理"]},{"name":"工程学院","majors":["电子工程","机械工程","土木工程","电脑科学","生物医学工程"]},{"name":"设计学院","majors":["工业设计","视觉传达","环境设计","多媒体设计","服装设计"]},{"name":"酒店及旅游业管理学院","majors":["酒店管理","旅游管理","会展管理","烹饪艺术"]}]', '[{"name":"商科类","majors":["金融学","会计学","工商管理","酒店管理","物流管理"]},{"name":"工科类","majors":["电子工程","机械工程","电脑科学","数据科学","人工智能"]},{"name":"设计类","majors":["工业设计","视觉传达","环境设计","服装设计","交互设计"]}]', 'HKD 130,000-170,000/年', 'https://www.polyu.edu.hk', 1, 0);

-- 香港浸会大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('香港浸会大学', 'Hong Kong Baptist University', '香港', '九龙九龙塘', 6, 'https://www.hkbu.edu.hk/images/about/campus_1.jpg', '香港浸会大学（HKBU）成立于1956年，是香港历史第二悠久的公立大学。浸大以传媒、文科、宗教研究等领域著称，传理学院被誉为"亚洲最强"。', '["传理学院亚洲第一","文理科均衡发展","研究实力强","地理位置优越","国际化氛围"]', '{"本科":"高考成绩达一本线以上80分，英语单科110+","硕士":"持有本科学位，GPA 2.8+，雅思6.5+"}', '[{"name":"文学院","majors":["中国语言文学","英文","历史学","哲学","宗教研究"]},{"name":"传理学院","majors":["新闻学","传播学","影视制作","数字媒体","公共关系"]},{"name":"商学院","majors":["会计学","金融学","工商管理","经济学","商业分析"]},{"name":"理学院","majors":["计算机科学","数学","物理学","化学","生物科学"]}]', '[{"name":"传媒类","majors":["新闻学","传播学","影视与新媒体","公共关系","媒体管理"]},{"name":"商科类","majors":["金融学","会计学","工商管理","商业分析","人力资源管理"]},{"name":"文科类","majors":["中国文学","语言学","历史学","翻译学","社会工作"]}]', 'HKD 120,000-160,000/年', 'https://www.hkbu.edu.hk', 1, 0);

-- 香港岭南大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('香港岭南大学', 'Lingnan University', '香港', '新界屯门', 7, 'https://www.ln.edu.hk/assets/images/2023/header-banner/about-campus.jpg', '香港岭南大学（Lingnan）成立于1888年，是香港历史最悠久的公立大学，也是亚洲领先的博雅大学。岭大以小班教学、紧密师生关系和全面发展著称。', '["博雅教育典范","小班教学","师资力量强","海外交流机会多","奖学金丰富"]', '{"本科":"高考成绩达一本线以上50分，英语单科110+","硕士":"持有本科学位，GPA 2.5+，雅思6.5+"}', '[{"name":"文学院","majors":["中文","英文","历史学","哲学","翻译"]},{"name":"商学院","majors":["会计学","金融学","工商管理","人力资源管理","市场营销"]},{"name":"社会科学院","majors":["心理学","社会学","政治学","经济学","社会工作"]}]', '[{"name":"商科类","majors":["金融学","会计学","工商管理","人力资源管理","市场营销"]},{"name":"文科类","majors":["中文研究","英文研究","历史学","翻译学","哲学"]},{"name":"社科类","majors":["心理学","社会学","国际关系","经济学","社会工作"]}]', 'HKD 110,000-140,000/年', 'https://www.ln.edu.hk', 1, 0);

-- 香港教育大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('香港教育大学', 'The Education University of Hong Kong', '香港', '新界大埔', 8, 'https://www.eduhk.hk/images/2022/05/banner-campus-overview.jpg', '香港教育大学（EdUHK）是香港唯一的师范类大学，致力培养优质教师和教育专业人才。教育学科在全球排名前列，是香港教师培训的主要基地。', '["教育学科全球领先","师范类权威","就业率高","实践机会多","师资优秀"]', '{"本科":"高考成绩达一本线以上50分，英语单科110+","硕士":"持有本科学位，GPA 2.5+，雅思6.0+"}', '[{"name":"教育学院","majors":["小学教育","中学教育","幼儿教育","特殊教育","教育心理学"]},{"name":"人文学院","majors":["中文","英文","历史学","地理学","音乐教育"]},{"name":"理学院","majors":["数学","科学","电脑科学","科技教育"]},{"name":"社会科学学院","majors":["心理学","社会学","公共政策","运动科学"]}]', '[{"name":"教育类","majors":["教育学","小学教育","中学教育","幼儿教育","特殊教育","教育心理学"]},{"name":"语言类","majors":["中文教育","英文教育","语言学","翻译教育"]},{"name":"社科类","majors":["心理学","社会学","公共政策","国际关系"]}]', 'HKD 100,000-130,000/年', 'https://www.eduhk.hk', 1, 0);

-- 澳门大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('澳门大学', 'University of Macau', '澳门', '氹仔', 1, 'https://www.um.edu.mo/wp-content/uploads/2022/06/campusbanner.jpg', '澳门大学（UM）成立于1981年，是澳门唯一的公立综合性大学。2024年QS世界大学排名第254位，亚洲大学排名前50。澳大采用书院制教育模式，优先发展中医药、微电子和物联网等特色学科。', '["QS世界大学排名前300","书院制教育","英文授课为主","奖学金丰厚","粤港澳大湾区优势"]', '{"本科":"高考成绩达一本线以上，英语单科110+","硕士":"持有本科学位，GPA 2.8+，雅思6.0+"}', '[{"name":"人文学院","majors":["中国语言文学","英文","历史学","哲学","艺术史"]},{"name":"工商管理学院","majors":["会计学","金融学","工商管理","商业经济学","市场学"]},{"name":"教育学院","majors":["教育学","小学教育","中学教育","幼儿教育","语言教育"]},{"name":"健康科学学院","majors":["生物医学","药物科学","公共卫生","护理学"]},{"name":"科技学院","majors":["计算机科学","电子工程","土木工程","机械工程","数学"]},{"name":"法学院","majors":["法学","法律研究","国际商法"]}]', '[{"name":"商科类","majors":["金融学","会计学","工商管理","商业分析","人力资源管理"]},{"name":"理工类","majors":["计算机科学","电子工程","数据科学","人工智能","机电工程"]},{"name":"医学类","majors":["生物医学","药物科学","公共卫生","护理学"]},{"name":"人文类","majors":["中国文学","语言学","历史学","教育学","心理学"]}]', 'MOP 100,000-120,000/年', 'https://www.um.edu.mo', 1, 0);

-- 澳门理工大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('澳门理工大学', 'Macao Polytechnic University', '澳门', '澳门半岛', 2, 'https://www.mpu.edu.mo/images/2023/banner-campus.jpg', '澳门理工大学（MPU）成立于1981年，是澳门重要的公立应用型大学。理工大以资讯科技、艺术设计、健康科学等应用学科为特色，与业界紧密合作，培养实用型人才。', '["应用型强","与业界紧密合作","就业率高","奖学金丰富","地理优势明显"]', '{"本科":"高考成绩达本科线以上，英语单科90+","硕士":"持有本科学位，GPA 2.5+，雅思5.5+"}', '[{"name":"资讯科技学院","majors":["电脑学","数据科学","人工智能","网络与安全"]},{"name":"艺术学院","majors":["视觉艺术","设计学","音乐学","数字媒体"]},{"name":"健康科学及体育学院","majors":["护理学","检验技术","物理治疗","体育管理"]},{"name":"语言及翻译学院","majors":["中英翻译","中葡翻译","国际葡萄牙语"]},{"name":"管理学院","majors":["会计学","电子商务","会展管理","旅游管理"]}]', '[{"name":"科技类","majors":["电脑科学","数据科学","人工智能","网络工程"]},{"name":"艺术类","majors":["视觉艺术","设计学","数字媒体","音乐学"]},{"name":"健康类","majors":["护理学","检验技术","物理治疗","公共卫生"]},{"name":"语言类","majors":["中英翻译","中葡翻译","葡萄牙语"]}]', 'MOP 80,000-100,000/年', 'https://www.mpu.edu.mo', 1, 0);

-- 澳门科技大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('澳门科技大学', 'Macau University of Science and Technology', '澳门', '氹仔', 3, 'https://www.must.edu.mo/wp-content/uploads/2021/03/2021-campus-1.jpg', '澳门科技大学（MUST）成立于2000年，是澳门规模最大的私立综合性大学。科技大学以中医药、酒店与旅游管理、电脑科学等学科为优势，与内地和海外高校合作密切。', '["规模最大","学科设置全面","科研实力强","与内地联系紧密","校园设施先进"]', '{"本科":"高考成绩达本科线以上，英语单科100+","硕士":"持有本科学位，GPA 2.5+，雅思5.5+"}', '[{"name":"中医药学院","majors":["中医学","中药学","针灸推拿学","中西结合"]},{"name":"酒店与旅游管理学院","majors":["酒店管理","旅游管理","会展管理","休闲管理"]},{"name":"电脑科学学院","majors":["电脑科学","软件工程","人工智能","数据科学","网络安全"]},{"name":"商学院","majors":["会计学","金融学","工商管理","市场营销","供应链管理"]},{"name":"法学院","majors":["法学","国际法","金融法","葡语法学"]},{"name":"人文艺术学院","majors":["新闻传播学","数字媒体艺术","影视制作","广播电视编导"]}]', '[{"name":"商科类","majors":["金融学","会计学","工商管理","市场营销","旅游管理"]},{"name":"科技类","majors":["电脑科学","人工智能","数据科学","软件工程"]},{"name":"医学类","majors":["中医学","中药学","护理学","公共卫生"]},{"name":"艺术类","majors":["数字媒体","影视制作","新闻传播","视觉传达"]}]', 'MOP 90,000-130,000/年', 'https://www.must.edu.mo', 1, 0);

-- 澳门城市大学
INSERT INTO schools (name_cn, name_en, country, city, `rank`, banner, description, features, requirements, faculties, master_categories, tuition, website, status, view_count) VALUES 
('澳门城市大学', 'City University of Macau', '澳门', '澳门半岛', 4, 'https://www.cityu.edu.mo/wp-content/uploads/2021/06/banner.jpg', '澳门城市大学（CityU）前身是成立于1981年的东亚大学，2011年更名为澳门城市大学。城大以旅游与酒店管理、商科、文化产业为特色，提供多层次的教育课程。', '["旅游管理见长","商科优势明显","地理位置优越","课程设置灵活","海外交流机会多"]', '{"本科":"高考成绩达本科线以上","硕士":"持有本科学位，GPA 2.5+，雅思5.0+"}', '[{"name":"旅游与酒店学院","majors":["旅游管理","酒店管理","会展管理","休闲产业管理"]},{"name":"商学院","majors":["会计学","金融学","工商管理","国际商务","市场营销"]},{"name":"人文社会科学学院","majors":["心理学","社会工作","英语","葡萄牙语"]},{"name":"数据科学学院","majors":["数据科学","人工智能","电脑科学"]},{"name":"教育学院","majors":["教育学","教学研究","幼儿教育"]}]', '[{"name":"商科类","majors":["金融学","会计学","工商管理","国际商务","市场营销"]},{"name":"旅游类","majors":["旅游管理","酒店管理","会展管理","休闲产业"]},{"name":"社科类","majors":["心理学","社会工作","英语","葡萄牙语"]},{"name":"科技类","majors":["数据科学","人工智能","电脑科学"]}]', 'MOP 70,000-90,000/年', 'https://www.cityu.edu.mo', 1, 0);
